@echo off
echo Installing dependencies...
call npm install
echo Installing gh-pages...
call npm install gh-pages --save-dev
echo Building project...
call npm run build
echo Deploying to GitHub Pages...
call npm run deploy
echo Done.
